In [19]:
import numpy as np
arr = np.array([23,56,78,90, 65])
print(arr)


[23 56 78 90 65]


In [20]:
b = np.array([[1,2,9, 7], [5,7,8, 4]])
print(b)
print(b.shape) # R x C

[[1 2 9 7]
 [5 7 8 4]]
(2, 4)


In [21]:
c = np.array([[[1,2, 5],[3,4, 7]], [[5,6,2],[7,8,1]], [[9,10, 11],[11,12,56]],  [[9,10, 11],[11,12,56]]])
print(c)

[[[ 1  2  5]
  [ 3  4  7]]

 [[ 5  6  2]
  [ 7  8  1]]

 [[ 9 10 11]
  [11 12 56]]

 [[ 9 10 11]
  [11 12 56]]]


In [4]:
print(c.shape)

(4, 2, 3)


In [22]:
np.array([1.5, 3.4, 7.8], dtype=float)

array([1.5, 3.4, 7.8])

In [6]:
c.dtype

dtype('int64')

In [7]:
np.arange(1, 24)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23])

In [8]:
np.arange(1,18,3)

array([ 1,  4,  7, 10, 13, 16])

In [9]:
np.arange(18).reshape(3,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.random.random((2,4))

array([[0.19010487, 0.39319096, 0.29915167, 0.76169644],
       [0.48876936, 0.10186595, 0.78387921, 0.12279534]])

In [13]:
np.full((3,3, 3), 86)

array([[[86, 86, 86],
        [86, 86, 86],
        [86, 86, 86]],

       [[86, 86, 86],
        [86, 86, 86],
        [86, 86, 86]],

       [[86, 86, 86],
        [86, 86, 86],
        [86, 86, 86]]])

In [14]:
# linspace: 3 things to be provided
# np.linspace(1, 10, 7, dtype=int)
np.linspace(-23, 23, 7, dtype=int)

array([-23, -16,  -8,   0,   7,  15,  23])

In [15]:
# np.linspace(1, 10, 20)
np.linspace(1, 10, 20, dtype=int)

array([ 1,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  8,
        9,  9, 10])

In [16]:
a1 = np.arange(12).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
a1 ** 8

array([[        0,         1,       256,      6561],
       [    65536,    390625,   1679616,   5764801],
       [ 16777216,  43046721, 100000000, 214358881]])

In [18]:
a1 == 11

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [25]:
a2 = np.arange(8).reshape(2,2,2)
a2

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [34]:
a2[0,1,1]

np.int64(3)

In [35]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
a1[0,]

array([0, 1, 2, 3])

In [46]:
a1[:,2]

array([ 2,  6, 10])