In [ ]:
import numpy as np
arr = np.array([23,56,78,90, 65])
print(arr)


[23 56 78 90 65]


In [ ]:
b = np.array([[1,2,9, 7], [5,7,8, 4]])
print(b)
print(b.shape) # R x C

[[1 2 9 7]
 [5 7 8 4]]
(2, 4)


In [ ]:
c = np.array([[[1,2, 5],[3,4, 7]], [[5,6,2],[7,8,1]], [[9,10, 11],[11,12,56]],  [[9,10, 11],[11,12,56]]])
print(c)

[[[ 1  2  5]
  [ 3  4  7]]

 [[ 5  6  2]
  [ 7  8  1]]

 [[ 9 10 11]
  [11 12 56]]

 [[ 9 10 11]
  [11 12 56]]]


In [ ]:
print(c.shape)

(4, 2, 3)


In [ ]:
np.array([1.5, 3.4, 7.8], dtype=float)

array([1.5, 3.4, 7.8])

In [ ]:
c.dtype

dtype('int64')

In [ ]:
np.arange(1, 55)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54])

In [ ]:
np.arange(1,18,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [ ]:
np.arange(18).reshape(3,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.random.random((2,4))

array([[0.90783626, 0.89737356, 0.88036618, 0.11901443],
       [0.89308441, 0.27063823, 0.91103452, 0.21824439]])

In [ ]:
np.full((3,3), 86)

array([[86, 86, 86],
       [86, 86, 86],
       [86, 86, 86]])