In [ ]:
import numpy as np
arr = np.array([23,56,78,90, 65])
print(arr)


[23 56 78 90 65]


In [ ]:
b = np.array([[1,2,9, 7], [5,7,8, 4]])
print(b)
print(b.shape) # R x C

[[1 2 9 7]
 [5 7 8 4]]
(2, 4)


In [ ]:
c = np.array([[[1,2, 5],[3,4, 7]], [[5,6,2],[7,8,1]], [[9,10, 11],[11,12,56]],  [[9,10, 11],[11,12,56]]])
print(c)

[[[ 1  2  5]
  [ 3  4  7]]

 [[ 5  6  2]
  [ 7  8  1]]

 [[ 9 10 11]
  [11 12 56]]

 [[ 9 10 11]
  [11 12 56]]]


In [ ]:
print(c.shape)

(4, 2, 3)


In [ ]:
np.array([1.5, 3.4, 7.8], dtype=float)

array([1.5, 3.4, 7.8])

In [ ]:
c.dtype

dtype('int64')

In [ ]:
np.arange(1, 24)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23])

In [ ]:
np.arange(1,18,3)

array([ 1,  4,  7, 10, 13, 16])

In [ ]:
np.arange(18).reshape(3,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.random.random((2,4))

array([[0.14624633, 0.88411739, 0.1719476 , 0.03366215],
       [0.26305569, 0.30679016, 0.04522431, 0.34659477]])

In [ ]:
np.full((3,3, 3), 86)

array([[[86, 86, 86],
        [86, 86, 86],
        [86, 86, 86]],

       [[86, 86, 86],
        [86, 86, 86],
        [86, 86, 86]],

       [[86, 86, 86],
        [86, 86, 86],
        [86, 86, 86]]])

In [ ]:
# linspace: 3 things to be provided
# np.linspace(1, 10, 7, dtype=int)
np.linspace(-23, 23, 7, dtype=int)

array([-23, -16,  -8,   0,   7,  15,  23])

In [ ]:
# np.linspace(1, 10, 20)
np.linspace(1, 10, 20, dtype=int)

array([ 1,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  8,
        9,  9, 10])

In [ ]:
a1 = np.arange(12).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a1 ** 8

array([[        0,         1,       256,      6561],
       [    65536,    390625,   1679616,   5764801],
       [ 16777216,  43046721, 100000000, 214358881]])

In [ ]:
a1 == 11

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [ ]:
a2 = np.arange(8).reshape(2,2,2)
a2

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a2[0,1,1]

np.int64(3)

In [ ]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a1[2,]

array([ 8,  9, 10, 11])

In [ ]:
a1[:,3]

array([ 3,  7, 11])

In [ ]:
a1[0:2, 2:4]

array([[2, 3],
       [6, 7]])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[1, 0:2, 1:3]

array([[10, 11],
       [13, 14]])

In [ ]:
a3[2, 0:, 1]

array([19, 22, 25])